download:
	cd delayed_binary; make download
	cd delayed_raw; make download
	cd realtime_binary; make download
	cd realtime_raw; make download
clean:
	-cd delayed_binary; make clean
	-cd delayed_raw; make clean
	-cd realtime_binary; make clean
	-cd realtime_raw; make clean
