language: r
warnings_are_errors: false
sudo: required
dist: trusty

r_packages:
    - oce
    - Rcurl
    - covr
env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False

after_success:
        - Rscript -e 'library(covr); codecov(type="all")'

