---
title: "Introduction to oceglider"
author: "Dan Kelley (https://orcid.org/0000-0001-7808-5911)"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    fig_caption: yes
    fig_width: 6
    fig_height: 4
    dpi: 72
vignette: >
  %\VignetteIndexEntry{Introduction to oceglider}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

**Abstract.** This vignette explains the basics of using the `oceglider`
package. Please note that the package is still a work in progress, with
functions evolving as the authors realize that new features might be helpful to
analysts working with glider data.

# History of the Package

The package started with code to read SeaExplorer data in what is called "raw"
form.  Functions are provided to work with both data telemetered back to base
as the glider is en-route, and with data downloaded after it is recovered.
These functions are named `read.glider.seaexplorer.delayed()` and
`read.glider.seaexplorer.realtime(),` respectively.

In addition to functions for reading such data, some specialized variants of
standard R functions, notably `plot()`, `summary()` and `[[`, were set up.
These differ from similar functions in the `oce` package both in the sorts of
plots that are offered and in handling the internal structure of the objects
used in the `oceglider` package (e.g. with the separation of payload and glider
                                 files, for the SeaExplorer devices).

The next stage in the evolution of the package was to handle Slocum data. The
functions `read.glider.slocum()` and `read.glider.slocum.netcdf()` were
designed for this work, but neither has been tested recently, because the
data servers being employed recently seem to store a more generic format that
is handled by `read.glider.netcdf()`.

Indeed, as of September 2024, it seems that many datasets are provided in a
format that `read.glider.netcdf()` can read.  A problem that is still
unresolved, here and generally for oceanographic data, is the naming convention
for variables (and units). Work is underway, both in the `oceglider` package
and the older and more general `oce` package, to handle the variety of names in
a more accurate manner, and in a way that lets users intercede when they know
the convention being used in a particular dataset.

Please consult the other vignettes for details on processing
various types of glider data.

# Further Reading

1. Integrated Ocean Observing System (U.S.). “Manual for Quality
   Control of Temperature and Salinity Data Observations from Gliders.
Version 1.0.” Report. U.S. Department of Commerce, National Oceanic
and Atmospheric Administration, National Ocean Service, Integrated
Ocean Observing System, U.S. Integrated Ocean Observing System, Glider
Data Assembly Center, 2016.
https://www.oceanbestpractices.net/handle/11329/289.

2. Integrated Ocean Observing System (U.S.). “NGDAC NetCDF File Format
   Version 2,” March 27, 2019.
https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2.

